# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Gradle Wrapper Validation
  # You may pin to the exact commit or the version.
  # uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Build with Gradle
        run: ./gradlew build -x :app:mergeDebugJavaResource -x :app:mergeReleaseJavaResource
      - name: Run Tests
        run: ./gradlew check
      - name: Archive Test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results
          path: |
            backend/build/test-results/**/*.xml
            app/build/test-results/**/*.xml
            shared/build/test-results/**/*.xml
          retention-days: 7
      - name: Archive Test Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-report
          path: |
            backend/build/reports/**/*
            app/build/reports/**/*
            shared/build/reports/**/*
          retention-days: 7
